# Generated by Django 3.2.11 on 2022-02-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolYard', '0002_auto_20220216_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='victory_condition',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='winner',
            new_name='status',
        ),
        migrations.AddField(
            model_name='history',
            name='csrf_token',
            field=models.CharField(default='Null', max_length=96),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='timestamp',
            field=models.CharField(default=1645023801.395453, max_length=24),
        ),
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.CharField(default='23:03:21', max_length=16),
        ),
    ]
