# Generated by Django 3.2.11 on 2022-02-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolYard', '0003_auto_20220216_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='winner',
            field=models.CharField(default='White', max_length=8),
        ),
        migrations.AlterField(
            model_name='history',
            name='computer_time_left',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='history',
            name='condition',
            field=models.CharField(default='In Progress', max_length=32),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.CharField(default='24 Feb 2022', max_length=16),
        ),
        migrations.AlterField(
            model_name='history',
            name='game_fen',
            field=models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=96),
        ),
        migrations.AlterField(
            model_name='history',
            name='moves',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='history',
            name='player_time_left',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(default='White', max_length=8),
        ),
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.CharField(default='00:16:22', max_length=16),
        ),
        migrations.AlterField(
            model_name='history',
            name='timestamp',
            field=models.CharField(default=1645632982.789915, max_length=24),
        ),
    ]
