# Generated by Django 3.2.11 on 2022-03-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolYard', '0004_auto_20220224_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.CharField(default='17 Mar 2022', max_length=16),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(default='White', max_length=48),
        ),
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.CharField(default='18:58:29', max_length=16),
        ),
        migrations.AlterField(
            model_name='history',
            name='timestamp',
            field=models.CharField(default=1647514709.253612, max_length=24),
        ),
        migrations.AlterField(
            model_name='history',
            name='winner',
            field=models.CharField(default='White', max_length=48),
        ),
    ]
