# Generated by Django 3.2.11 on 2022-03-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolYard', '0006_auto_20220317_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.CharField(default='19:42:07', max_length=16),
        ),
        migrations.AlterField(
            model_name='history',
            name='timestamp',
            field=models.CharField(default=1647517327.55605, max_length=24),
        ),
    ]
